services:
  - type: web
    name: media-api-server
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y nodejs npm phantomjs
      pip install -r requirements.txt
    startCommand: python main.py
